{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-user-sync.secretName" . }}
  labels:
    {{- include "ldap-user-sync.labels" . | nindent 4 }}
type: Opaque
data:
  ldap-bind-password: {{ .Values.secrets.ldapBindPassword | b64enc | quote }}
  {{- range $index, $vendor := .Values.vendors }}
  {{- $vendorNum := add $index 1 }}
  {{- if eq $vendor.auth.method "basic" }}
  vendor{{ $vendorNum }}-username: {{ index $.Values.secrets (printf "vendor%dUsername" $vendorNum) | b64enc | quote }}
  vendor{{ $vendorNum }}-password: {{ index $.Values.secrets (printf "vendor%dPassword" $vendorNum) | b64enc | quote }}
  {{- else if eq $vendor.auth.method "token" }}
  vendor{{ $vendorNum }}-token: {{ index $.Values.secrets (printf "vendor%dToken" $vendorNum) | b64enc | quote }}
  {{- end }}
  {{- end }}
  smtp-username: {{ .Values.secrets.smtpUsername | b64enc | quote }}
  smtp-password: {{ .Values.secrets.smtpPassword | b64enc | quote }}
{{- end }}